import { Shelter, Need, ItemType, Urgency, Status } from './types';

export const MOCK_SHELTERS: Shelter[] = [
  { id: 'shelter-1', name: 'Mary\'s Place Family Center', address: '123 Elliott Ave', city: 'Seattle', state: 'WA', email: 'contact@marysplace.org', phone: '206-555-0101', lat: 47.6062, lng: -122.3321 },
  { id: 'shelter-2', name: 'FareStart Downtown', address: '700 Virginia St', city: 'Seattle', state: 'WA', email: 'info@farestart.org', phone: '206-555-0102', lat: 47.6152, lng: -122.3385 },
  { id: 'shelter-3', name: 'Union Gospel Mission', address: '318 2nd Ave Ext S', city: 'Seattle', state: 'WA', email: 'connect@ugm.org', phone: '206-555-0103', lat: 47.5982, lng: -122.3307 },
  { id: 'shelter-4', name: 'YouthCare Orion Center', address: '1828 Yale Ave', city: 'Seattle', state: 'WA', email: 'support@youthcare.org', phone: '206-555-0104', lat: 47.6171, lng: -122.3301 },
  { id: 'shelter-5', name: 'Compass Housing Alliance', address: '77 S Washington St', city: 'Seattle', state: 'WA', email: 'info@compasshousingalliance.org', phone: '206-555-0105', lat: 47.5999, lng: -122.3325 },
  { id: 'shelter-6', name: 'Tacoma Rescue Mission', address: '425 South Tacoma Way', city: 'Tacoma', state: 'WA', email: 'info@trm.org', phone: '253-555-0106', lat: 47.248, lng: -122.449 },
  { id: 'shelter-7', name: 'Hope House', address: '111 W 3rd Ave', city: 'Spokane', state: 'WA', email: 'contact@hopehouse.org', phone: '509-555-0107', lat: 47.653, lng: -117.424 },
  { id: 'shelter-8', name: 'The Sophia Way', address: '3032 Bellevue Way NE', city: 'Bellevue', state: 'WA', email: 'support@sophiaway.org', phone: '425-555-0108', lat: 47.632, lng: -122.199 },
  { id: 'shelter-9', name: 'Renton Salvation Army', address: '720 S Tobin St', city: 'Renton', state: 'WA', email: 'info@rentonsa.org', phone: '425-555-0109', lat: 47.478, lng: -122.208 },
  { id: 'shelter-10', name: 'Kent Hope', address: '900 E Smith St', city: 'Kent', state: 'WA', email: 'support@kenthope.org', phone: '253-555-0110', lat: 47.382, lng: -122.222 },
  { id: 'shelter-11', name: 'Multi-Service Center', address: '1200 S 336th St', city: 'Federal Way', state: 'WA', email: 'contact@mschelps.org', phone: '253-555-0111', lat: 47.303, lng: -122.311 },
  { id: 'shelter-12', name: 'Hospitality House', address: '1419 SW 150th St', city: 'Burien', state: 'WA', email: 'info@hospitalityhouse.org', phone: '206-555-0112', lat: 47.471, lng: -122.355 },
];

export const MOCK_NEEDS: Need[] = [
  { id: 'need-1', shelterId: 'shelter-1', itemType: ItemType.Clothing, name: "Men's Winter Jackets", originalQuantity: 50, quantity: 50, urgency: Urgency.High, description: "Need warm winter jackets for adult men, sizes M-XL.", status: Status.Active },
  { id: 'need-2', shelterId: 'shelter-1', itemType: ItemType.Food, name: "Canned Vegetables", originalQuantity: 200, quantity: 200, urgency: Urgency.Medium, description: "Canned corn, green beans, and peas are most needed.", status: Status.Active },
  { id: 'need-3', shelterId: 'shelter-2', itemType: ItemType.Hygiene, name: "Toothpaste", originalQuantity: 100, quantity: 100, urgency: Urgency.Medium, description: "Standard size toothpaste tubes.", status: Status.Active },
  { id: 'need-4', shelterId: 'shelter-3', itemType: ItemType.Blankets, name: "Warm Blankets", originalQuantity: 75, quantity: 75, urgency: Urgency.High, description: "Twin size warm blankets or sleeping bags.", status: Status.Active },
  { id: 'need-5', shelterId: 'shelter-2', itemType: ItemType.Food, name: "Fresh Bread", originalQuantity: 50, quantity: 10, urgency: Urgency.Low, description: "Loaves of bread for daily sandwiches.", status: Status.Pending },
  { id: 'need-6', shelterId: 'shelter-4', itemType: ItemType.Clothing, name: "Children's Shoes", originalQuantity: 30, quantity: 30, urgency: Urgency.High, description: "Various sizes for children ages 5-12.", status: Status.Active },
  { id: 'need-7', shelterId: 'shelter-3', itemType: ItemType.Other, name: "Diapers", originalQuantity: 150, quantity: 0, urgency: Urgency.Medium, description: "Size 4 and 5 diapers.", status: Status.Fulfilled },
  { id: 'need-8', shelterId: 'shelter-5', itemType: ItemType.Food, name: "Peanut Butter", originalQuantity: 60, quantity: 60, urgency: Urgency.Medium, description: "16oz jars of peanut butter.", status: Status.Active },
  { id: 'need-9', shelterId: 'shelter-1', itemType: ItemType.Hygiene, name: "Shampoo", originalQuantity: 80, quantity: 80, urgency: Urgency.Low, description: "Full-size bottles of shampoo.", status: Status.Active },
  { id: 'need-10', shelterId: 'shelter-4', itemType: ItemType.Other, name: "Bus Passes", originalQuantity: 100, quantity: 100, urgency: Urgency.High, description: "Single-day ORCA bus passes for job interviews and appointments.", status: Status.Active },
  { id: 'need-11', shelterId: 'shelter-2', itemType: ItemType.Clothing, name: "New Socks", originalQuantity: 300, quantity: 150, urgency: Urgency.High, description: "New pairs of socks for adults.", status: Status.Pending },
  { id: 'need-12', shelterId: 'shelter-3', itemType: ItemType.Food, name: "Bottled Water", originalQuantity: 500, quantity: 0, urgency: Urgency.Medium, description: "Cases of bottled water are greatly appreciated.", status: Status.Fulfilled },
  { id: 'need-13', shelterId: 'shelter-5', itemType: ItemType.Blankets, name: "Sleeping Bags", originalQuantity: 25, quantity: 25, urgency: Urgency.High, description: "Durable, all-weather sleeping bags for adults.", status: Status.Active },
  { id: 'need-14', shelterId: 'shelter-1', itemType: ItemType.Other, name: "Children's Books", originalQuantity: 50, quantity: 50, urgency: Urgency.Low, description: "New or gently used books for children ages 3-10.", status: Status.Active },
  { id: 'need-15', shelterId: 'shelter-2', itemType: ItemType.Hygiene, name: "Feminine Hygiene Products", originalQuantity: 120, quantity: 120, urgency: Urgency.Medium, description: "Pads and tampons are urgently needed.", status: Status.Active },
  { id: 'need-16', shelterId: 'shelter-6', itemType: ItemType.Food, name: "Pasta and Sauce", originalQuantity: 100, quantity: 100, urgency: Urgency.Medium, description: "Boxes of pasta and jars of marinara sauce.", status: Status.Active },
  { id: 'need-17', shelterId: 'shelter-7', itemType: ItemType.Clothing, name: "Women's Coats", originalQuantity: 40, quantity: 40, urgency: Urgency.High, description: "Warm winter coats for adult women, all sizes.", status: Status.Active },
  { id: 'need-18', shelterId: 'shelter-8', itemType: ItemType.Hygiene, name: "Soap and Deodorant", originalQuantity: 150, quantity: 150, urgency: Urgency.Medium, description: "Bars of soap and sticks of deodorant.", status: Status.Active },
  { id: 'need-19', shelterId: 'shelter-6', itemType: ItemType.Blankets, name: "Towels", originalQuantity: 80, quantity: 80, urgency: Urgency.Low, description: "New or gently used bath towels.", status: Status.Active },
  { id: 'need-20', shelterId: 'shelter-7', itemType: ItemType.Other, name: "First-Aid Kits", originalQuantity: 30, quantity: 30, urgency: Urgency.High, description: "Basic first-aid kits with bandages, antiseptic wipes, etc.", status: Status.Active },
  { id: 'need-21', shelterId: 'shelter-9', itemType: ItemType.Food, name: "Baby Formula", originalQuantity: 50, quantity: 50, urgency: Urgency.High, description: "Enfamil or Similac powdered formula.", status: Status.Active },
  { id: 'need-22', shelterId: 'shelter-10', itemType: ItemType.Clothing, name: "Teenager Hoodies", originalQuantity: 60, quantity: 60, urgency: Urgency.Medium, description: "Sizes S-XL for teenagers.", status: Status.Active },
  { id: 'need-23', shelterId: 'shelter-11', itemType: ItemType.Hygiene, name: "Hand Sanitizer", originalQuantity: 100, quantity: 100, urgency: Urgency.Low, description: "Large refill bottles or individual travel-size bottles.", status: Status.Active },
  { id: 'need-24', shelterId: 'shelter-12', itemType: ItemType.Blankets, name: "Pillows", originalQuantity: 40, quantity: 40, urgency: Urgency.Medium, description: "New standard-size pillows.", status: Status.Active },
  { id: 'need-25', shelterId: 'shelter-9', itemType: ItemType.Other, name: "Pet Food", originalQuantity: 30, quantity: 30, urgency: Urgency.Low, description: "Bags of dry dog and cat food.", status: Status.Active },
];